#!/bin/sh

set -o nounset
#set -o pipefail

if ! command -v aspell > /dev/null; then
    SDKExitFatal "Missing aspell utility"
elif ! aspell dump dicts | grep -qw "en$" > /dev/null ; then
    SDKExitFatal "Missing aspell English dictionary (aspell-en)"
fi

DATAFILE=$(mktemp /tmp/lynis-strings.XXXXXXXXXX)
DATAFILE_SORTED=$(mktemp /tmp/lynis-strings-sorted.XXXXXXXXXX)

echo "Temporary file: ${DATAFILE}"
strings ../lynis/lynis > "${DATAFILE}"
find ../lynis/include -type f -exec strings {} \; | tr ' ' '\n' >> "${DATAFILE}"


# tr    delete quotes (disabled) #    tr -d "'" | \
# tr    split key/value pairs
# tr    split words or paths
# grep  get all words 4 characters or more
# sed   strip out unwanted characters
# grep  ignore uppercase words (2 or more capitals)
# grep  ignore words with underscores (most likely variables)
# grep  ignore words with dots
# awk   count number of capitals by doing a replacement and showing word + count
# awk   only show items that have one capital max
# grep  another run to get rid of very short words
# tr    turn all words into lowercase before sorting
# sort  sort and only store unique words


< "${DATAFILE}" \
    tr '=' ' ' | \
    tr '/' ' ' | \
    grep -E "^[a-zA-Z]{4,}" | \
    sed -e 's/[|?#,:"\{\}\$=\(\)\;\/]//g' | \
    tr ' ' '\n' | \
    grep -E -v "^[A-Z]{2,}" | \
    grep -v "_" | \
    grep -v "\." | \
    awk '{print $1,gsub("[A-Z]","")}' | \
    awk '{if ($2 <= 1) { print $1 }}' | \
    grep -E "^[a-zA-Z]{4,}" | \
    tr '[:upper:]' '[:lower:]' | \
    sort --unique > "${DATAFILE_SORTED}"

aspell --lang=en --ignore-case --personal=./grammar/words-to-ignore.en.pws check "${DATAFILE_SORTED}"

if [ -f "${DATAFILE}" ]; then rm "${DATAFILE}"; fi
if [ -f "${DATAFILE_SORTED}" ]; then rm "${DATAFILE_SORTED}"; fi
