#!/bin/sh

    SDKBuildPackageDPKG() {
        if [ -x /usr/bin/dpkg ]; then
            dpkg -l dpkg-dev | grep "^ii" | grep "dpkg-dev" > /dev/null || SDKExitFatal "Package 'dpkg-dev' not installed"
            dpkg -l debhelper | grep "^ii" | grep "debhelper" > /dev/null || SDKExitFatal "Package 'debhelper' not installed"
          else
            echo "Warning: no check for packages performed"
        fi
        #apt-get install dpkg-dev
        #apt-get install debhelper
        #dpkgbuild-package -us -uc -b
        echo "Building DPKG"
        dpkg-buildpackage -b -us -uc
        echo " ----"
    }

    SDKBuildPackageRPM() {
        echo "Building RPM"
        if [ -x /usr/bin/dpkg ]; then
            dpkg -l rpm | grep "^ii" | grep "rpm" > /dev/null || SDKExitFatal "Package 'rpm' not installed"
          else
            echo "Warning: no check for packages performed"
        fi
        DIRS="BUILD BUILDROOT RPMS SOURCES SRPMS"
        for DIR in ${DIRS}; do
            if [ ! -d ~/lynis-build/rpmbuild/${DIR} ]; then mkdir -p ~/lynis-build/rpmbuild/${DIR}; fi
        done
        ls -l ./tmp/lynis-build/rpmbuild
        tar --create -z -f ~/lynis-build/rpmbuild/SOURCES/lynis-${LYNIS_VERSION}.tar.gz ../lynis/*
        SDKShowLine
        ls -l ./tmp/lynis-build/rpmbuild/SOURCES/lynis-${LYNIS_VERSION}.tar.gz
        SDKShowLine
        rpmbuild -ba ./package-building/lynis.spec
        SDKShowLine

    }

    SDKExitFatal() {
        echo "$1"
        exit 1
    }

    SDKShowLine() {
        echo "==============================================================="
    }

    SDKPrintFailed() {
        printf " FAILED\n"
    }

    SDKPrintOK() {
        printf " OK\n"
    }


# EOF