#!/bin/sh

   # Check number of parameters submitted (at least one is needed)
    PARAMCOUNT=$#
    while [ $# -ge 1 ]; do
        case $1 in
            # Build
            build)
                if [ $# -ge 2 ]; then
                    case $2 in
                        "all")
                            MODE="build-all"
                        ;;
                        "deb" | "dpkg")
                            MODE="build-deb"
                        ;;
                        "rpm")
                            MODE="build-rpm"
                        ;;
                    esac
                else
                    echo "Error: Need a target to run"
                    echo " "
                    echo "Examples:"
                    echo "$0 build all"
                    echo "$0 build deb"
                    echo "$0 build rpm"
                    exit 1
                fi
            ;;

            # Helpers first
            run)
                if [ $# -ge 2 ]; then
                    case $2 in
                        "checks")
                            MODE="run-checks"
                        ;;
                        "linters")
                            MODE="run-linters"
                        ;;
                        "spelling-check")
                            MODE="run-spelling-check"
                        ;;
                        "unit-tests")
                            MODE="run-unit-tests"
                        ;;
                        *)
                            echo "Unknown 'run' command: $2"
                            exit 1
                        ;;
                    esac
                  else
                    echo "Error: Need a target to run"
                    echo " "
                    echo "Examples:"
                    echo "$0 run checks"
                    echo "$0 run linters"
                    echo "$0 run unit-tests"
                    exit 1
                fi
            ;;

            # Helpers first
            update)
                if [ $# -ge 2 ]; then
                    case $2 in
                        "language-files")
                            MODE="update-language-files"
                        ;;
                        *)
                            echo "Unknown 'update' command: $2"
                            exit 1
                        ;;
                    esac
                  else
                    echo "Error: Need a target to run"
                    echo " "
                    echo "Examples:"
                    echo "$0 update language-files"
                    exit 1
                fi
            ;;


        esac
        shift
    done
