#!/bin/sh

   # Check number of parameters submitted (at least one is needed)
    PARAMCOUNT=$#
    while [ $# -ge 1 ]; do
        case $1 in
            # Build
            build)
                if [ $# -ge 2 ]; then
                    case $2 in
                        "all")
                            MODE="build-all"
                        ;;
                        "dpkg")
                            MODE="build-dpkg"
                        ;;
                        "rpm")
                            MODE="build-rpm"
                        ;;

                    esac
                  else
                    echo "Error: Need a target to run"
                    echo " "
                    echo "Examples:"
                    echo "$0 build all"
                    echo "$0 build dpkg"
                    echo "$0 build rpm"
                    exit 1
                fi
            ;;

            # Helpers first
            run)
                if [ $# -ge 2 ]; then
                    case $2 in
                        "linters")
                            MODE="run-linters"
                        ;;
                        "unit-tests")
                            MODE="run-unit-tests"
                        ;;
                    esac
                  else
                    echo "Error: Need a target to run"
                    echo " "
                    echo "Examples:"
                    echo "$0 run linters"
                    echo "$0 run tests"
                    exit 1
                fi
            ;;


        esac
        shift
    done

